 # адрес, на котором хостится Торрсервер
 # если сервер удалённый, стоит также отключить автозапуск ниже в настройках
server=http://localhost:8090

 # поиск внешних субтитров и аудиодорожек в торрент-раздаче (их названия должны начинаться с названий соответствующих видеофайлов)
search_for_external_tracks=yes

 # максимальное время ожидания ответа (плейлиста с видео, полученного из магнет-ссылки)
response_timeout=15

 # автозапуск локального Торрсервера при открытии торрента, если он не был запущен или вылетел
autorun_torrserver=yes

 # откл: использовать "портативный" кроссплатформенный режим запуска TorrServer
 # (сервер будет автоматически закрываться вместе с плеером)
 # вкл: запускать сервер с помощью TorrServer Launcher (только на Windows):
 # сервер останется запущенным до перезапуска ПК, и его можно будет закрыть с помощью значка в трее
use_torrserver_launcher=no

 # выводить логи Торрсервера в консоль плеера (только при "портативном" режиме запуска)
print_server_logs=no

 # путь к папке, в которой лежат файлы Торрсервера ('~~/' - папка с mpv.conf)
torrserver_dir=~~/TorrServer

 # название исполняемых файлов TorrServer и TorrServer Launcher
ts_name=TorrServer-windows-amd64.exe
tsl_name=tsl.exe

 # автоматическая перезагрузка неудачно загрузившихся внешних субтитров
 # (такое случается нечасто и только на торрентах онлайн, может занять 5-30 сек)
auto_reload_failed_loading_subs=yes

 # включать в плейлист торрента файлы, не опознанные как видео или аудио
include_unknown=yes

 # при открытии ссылок на Торрсервер всегда подключаться к указанному в настройках адресу, даже если в ссылке написан другой
correct_server_links=no


 # Настройки горячих клавиш (пустая строка для отключения):
 # открыть оверлей со статистикой воспроизводимого торрента
key_toggle_stats=Ctrl+i

 # открыть веб-интерфейс TorrServer в браузере по умолчанию
key_toggle_in_browser=Ctrl+t

 # копировать магнет-ссылку текущей раздачи (без включённых трекеров-анонсеров)
key_copy_magnet=Ctrl+m


 # Настройки отображения статистики торрента:
 # размер шрифта текста статистики
stats_font_size=20

 # размер контуров вокруг текста
stats_font_border=1.2

 # масштабировать текст вместе с окном плеера (no|yes|auto), auto - в соответствии с опцией mpv --osd-scale-by-window
scale_stats_by_window=auto

 # размер буферов скорости и кэша в секундах на экране статистики
stats_buffer_size=20

 # автоматически открывать статистику на время первоначальной загрузки видео (no|yes|always)
 # yes - только при открытии новой торрент-раздачи, always - также и при смене файлов внутри раздачи
stats_autoshow=no

 # показывать названия торрентов и текущих файлов на экране статистики
stats_show_titles=yes

 # показывать инфо-хэш текущей раздачи
stats_show_hash=yes

 # показывать сетевую задержку до TorrServer (актуально только для удалённых серверов)
stats_show_latency=no
