 # Адрес, с которого получать сегменты SponsorBlock
server=https://sponsor.ajay.app/api/skipSegments

 # Категории для автопропуска
 # Доступные: sponsor (спонсорская реклама), selfpromo (самореклама), interaction (просьбы подписаться), intro (заставка), outro (концовка),
 # preview (краткое содержание), music_offtopic (тишина в музыкальных роликах), filler (не относящееся к сути), hook (завязка / приветствие)
categories=sponsor,selfpromo,interaction

 # Категории для пропуска вручную с помощью кнопки или горячей клавиши
notice_categories=intro,outro,music_offtopic,preview

 # Пропускать автоматически каждый сегмент лишь раз
skip_once=yes

 # Вместо ID видео передавать лишь начало его SHA256 хэша для большей приватности при запросе сегментов
 # (сервер не сможет определить точно просматриваемый ролик, поскольку передаваемый хэш одинаков сразу у многих видео)
hash=true

 # Использовать тот же прокси для получения и отправки сегментов, что и для самого видео
pass_proxy=yes

 # Горячая клавиша для ручного пропуска, когда он доступен
skip_key=Del
 # Клавиша для открытия меню отправки нового сегмента
submit_key=u
 # Клавиша для включения/выключения скрипта
toggle_key=

 # 32-символьный User ID, используемый при отправке сегментов SponsorBlock
 # оставьте пустым, чтобы использовать и хранить случайно сгенерированный
user_id=
 # Время перед началом нового сегмента при переходе в режим предпросмотра
preview_offset=2

 # Позиция кнопки для пропуска относительно окна плеера:
 # положительные значения - от верхнего/левого края окна, отрицательные - от правого/нижнего
skip_notice_pos_x=-20
skip_notice_pos_y=-90
 # Коэффициенты масштабирования кнопки и координат выше в оконном и полноэкранном режимах
scale=1
scale_fullscreen=1.3
 # Длительность отображения кнопки в секундах при заходе в сегмент для пропуска
persist_duration=3.5
 # Время до скрытия кнопки при отсутствии движений мыши
osc_duration=2
 # Продолжительность анимаций появления и скрытия кнопки
fade_in_duration=0.15
fade_out_duration=0.25
 # Прозрачность кнопки при совершённом автопропуске
opacity_after_skip=0.75
 # Прозрачность кнопки после скрытия
min_opacity=0

 # По умолчанию сегменты SponsorBlock дополнительно извлекаются лишь из глав,
 # образованных на скачанных yt-dlp роликах с опцией --sponsorblock-mark
 # Можно также задать собственные шаблоны для извлечения сегментов из глав видео,
 # если для текущего ролика не удалось или невозможно получить сегменты напрямую из SponsorBlock
custom_chapter_patterns=no

 # Список шаблонов Lua, разделённый '|', который проверяет на соответствие названия глав для каждой категории SponsorBlock
 # Синтаксис тот же, что и в опции exclude встроенного в mpv скрипта ytdl_hook:
 # ^ обозначает начало названия, $ - его конец, и нужно ставить % перед каждым из этих символов ^$()%|,.[]*+-? чтобы обозначить его
 # Для учёта регистра в конкретном шаблоне поместите в него хотя бы одну заглавную букву,
 # иначе же сравнение с названием главы будет без учёта регистра
sponsor_patterns=^ad$|^advertisement$|^pre%-?roll$|^реклама$
selfpromo_patterns=
interaction_patterns=
intro_patterns=^OP$|^OP |^opening$|^intro$|опенинг|оупенинг|интро|заставка
outro_patterns=^ED$|^ED |^ending$|^ending |^outro|credits$|^end$|эндинг|^титры
preview_patterns=^next$|^preview$|^PV$|^recap$|^далее$|^далее 
music_offtopic_patterns=
filler_patterns=
hook_patterns=