 # Экстрактор, используемый для получения медиапотоков и метаданных. Сейчас доступны (в порядке стабильности): 
 # visionos, visionos_reel (по умолчанию), android_vr, android_vr_reel, ios_reel, android_reel, ios, web (только метаданные)
 # Reel-экстракторы также извлекают доп. метаданные (дата публикации, число лайков, комментариев...) при том же числе запросов
 # Можно выбрать сразу несколько, вписав через запятую, но рекомендую вместо этого настроить ниже экстракторы для доп. парсинга лишь при необходимости
extractor=default
 
 # Скачивать и парсить ли HLS манифесты при наличии (no | auto | yes). 
 # auto - скачивать лишь в случае, если форматы из манифеста, скорее всего, будут выбраны по умолчанию
 # При отключении прямые трансляции не будут открываться!
parse_hls_manifests=auto
 # Скачивать ли данные веб-плеера для получения раскадровки в хорошем качестве и доп. метаданных параллельно с основным парсингом
 # Эти данные могут прибыть уже после открытия ролика; чтобы выполнить последовательный парсинг, можно добавить 'web' в список экстакторов
parse_web_player_async=yes

 # Разрешение видео, выбираемое по умолчанию
target_resolution=1440
 # Избегать ли AV1 кодек, если для желаемого качества доступны другие
skip_av1=yes
 # Избегать ли VP9 кодек, если для желаемого качества доступны другие
skip_vp9=no
 # Избегать ли HDR форматы
skip_hdr=yes
 # Пропускать ли ИИ-апскейлы от Ютуба при выборе качества
skip_ai_upscale=no
 # Пропускать ли ИИ-озвучки от Ютуба при выборе аудиодорожки
skip_ai_dub=yes
 # Предпочитать ли дорожки "Постоянный уровень громкости"
prefer_drc=no

 # Выбираемый формат субтитров. Доступны: vtt | srt | srv3 | ttml
sub_format=vtt
 # Язык метаданных, возвращаемых парсером
metadata_lang=ru
 # Язык аудиодорожки по умолчанию (пустое поле - выбор оригинальной), а также язык автопереведённых субтитров, загружаемых опцией ниже
translation_lang=ru
 # none - относиться к автоматическим субтитрам как к обычным, загружать автопереведённые на выбранном выше языке
 # deselect - добавлять автоматические субтитры в список, но не выбирать по умолчанию; загружать автопереведённые
 # skip-translated - добавлять только авто-сгенерированные субтитры в список и не выбирать их по умолчанию
 # skip - пропускать все автоматические субтитры
auto_subs_action=deselect

 # Экстрактор, дополнительно используемый, если для ролика может быть доступен поток "1080p Premium"
premium_extractor=
 # Экстрактор, испольуемый для YT Kids роликов, если выбранный по умолчанию их не открывает
yt_kids_extractor=ios_reel
 # Экстрактор, используемый для получения дорожек с переводами в мультиязычных видео, если основной их не предоставляет
dubbed_tracks_extractor=
 # Экстрактор, используемый для получения потоков на прямых трансляциях
livestream_extractor=android_vr_reel
 # Прокси, используемый для открытия роликов с региональными ограничениями. Прокси, выставленный в плеере, используется автоматически
 # Работает только при использовании английского и русского языков метаданных
geoblock_proxy=

 # Путь к исполняемому файлу curl, используемому для парсинга
curl_path=curl
 # Путь к файлу кэша, используемому для ускорения первого ("холодного") парсинга после запуска плеера (пустое поле для отключения)
cache_path=~~/youtube_parser_cache.json

 # Выводить ли дополнительно на экран ошибки парсинга
osd_errors=yes